### ISSUE TITLE
Scaling issue on secondary monitor at different dpi to primary - Windows Forms bug? 

### ISSUE THREAD

**Issue by mikeclayton** [mikeclayton/FancyMouse#2]
The first time the thumbnail is activated on a monitor it uses the scaling mode from the *previous* activation. In the case of the *very* first activation it uses the scaling mode of the primary monitor...

For example:

![image](https://user-images.githubusercontent.com/1193763/216848701-28da3dec-60b5-4422-877e-88bd7f68a118.png)

If the form is activated for the first time on Monitor 1 it will be set to the correct pixel size (e.g. 1600 x 453 in the image below) but it will be *drawn* at the wrong scale - 150% of (1600 x 453) = (2400 x 679).

![image](https://user-images.githubusercontent.com/1193763/216849120-10f3ac23-d6a5-4eae-82ea-b9f0db521177.png)

Re-activating the form immediately by pressing the hotkey combination causes the form to be re-drawn with the same pixel dimensions but at the correct scale...

![image](https://user-images.githubusercontent.com/1193763/216849091-8d78223d-30c5-4c43-8960-d69e8832ff22.png)

**Comment by mikeclayton** [comment]
Inverting the dpi causes the same issue, but with the opposite scaling:

![image](https://user-images.githubusercontent.com/1193763/216849220-6913826b-0b47-45cb-b7a1-0b6544aac21e.png)

resulting in the form being rendered at 100% (active dpi) / 150% (primary dpi) of (1600 x 453) = (1066 x 303):

![image](https://user-images.githubusercontent.com/1193763/216849575-72caa382-8637-443a-abed-3ab9a656e93f.png)

**Comment by mikeclayton** [comment]
Looks like it might be related to:

* https://github.com/dotnet/winforms/issues/4854

and might also be the root cause of:

* https://github.com/mikeclayton/FancyMouse/pull/1

**Comment by conradcn** [comment]
FWIW, my system has no DPI scaling on any screen, so I don't think it's related to the mouse sticking issue. Adding a second call to move the mouse fixed that for me (it might also be related to other software. I also run DisplayFusion and a lot of other stuff).

**Comment by mikeclayton** [comment]
Fixed in latest main branch.

For reasons I don't quite understand, using *this* specific sequence of code:

```csharp
        this.Location = formBounds.Location;
        _ = this.PointToScreen(Point.Empty);
        this.Size = formBounds.Size;
```

instead of 

```csharp
        this.Bounds = formBounds;
```

seems to fix the incorrect scaling for monitors that have different dpi.
