### ISSUE TITLE
Improve screenshot performance

### ISSUE THREAD

**Issue by mikeclayton** [mikeclayton/FancyMouse#4]
FancyMouse currently takes a screenshot using [```Graphics.CopyFromScreen```](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.graphics.copyfromscreen?view=dotnet-plat-ext-7.0) which captures the entire bounding rectangle of all monitors, and then allows the PictureBox scaling mode to shrink the image to the correct size.

This works, but is inefficient for "jagged" monitor layouts - for example this (contrived) setup:

![image](https://user-images.githubusercontent.com/1193763/220208985-c4784b82-3637-437d-a21d-b64dc29c68da.png)

In this setup the full desktop image captured by ```CopyFromScreen``` (in hot pink) is 81M  pixels, but the total visible screen area is only about 16M pixels so we're shifting around and scaling about 5 x the number of pixels we really need to be be handling due to the dead area around the screens, which means we're using more CPU to process the pixels and more memory to store them.

Investigate options for reducing the CPU / Memory usage.

Some options are:

* Copy the visible areas of each screen and compose them into the full-size preview image in multiple steps rather than copy the full desktop area in a single step (i.e. copy screen area 1, then screen area 2, etc)
* Manually resize the preview image to the correct size before assigning to the PictureBox so we don't hold the full-size image in memory. Potentially use fast low-quality resizing settings to speed this up.
* Use [```BitBlt```](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-bitblt) directly instead of ```CopyFromScreen```, which is a thin wrapper around ```BitBlt```. This might not improve performance much, but worth a shot....
* Use [```StretchBlt```](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-stretchblt) to copy  and stretch individual screen images at the same time
* Attempt to parallelise the capture of individual screen images
* Use hardware acceleration / DirectX where available

**Comment by oSumAtrIX** [comment]
Another thing that can improve performance is not to copy every pixel. The window which appears is considerably smaller which means the number of pixels that are used to display the screenshot is considerably smaller than the screenshot taken. A copy of each X pixel can be taken where X can be calculated based on the window size to improve performance. A lower-level approach to copying the pixels will be necessary.

**Comment by mikeclayton** [comment]
I've added a few different approaches to taking the screenshot in a stand-alone set of performance tests:

* **DefaultScreenCopyHelper.cs** - uses the current ```graphics.CopyFromScreen``` method that takes a full size screenshot including all of the dead area outside the bounds of screens, and relies on the PictureBox to scale the preview image to the appropriate size

* **ScalingScreenHelper.cs** - also uses ```graphics.CopyFromScreen``` but scales the image using ```graphics.DrawImage``` to scale the image at a lower resolution than the PictureBox deos

* **CsWin32JigsawCopyHelper.cs** - uses the [CsWin32](https://github.com/microsoft/CsWin32) library to generate Win32 API calls to [```StretchBltMode```](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-stretchblt) to scale and capture individual screen areas and composite them into a single image

* **ParallelScreenCopyHelper.cs** - similar to CsWin32JigsawCopyHelper, but tries to take parallel screesnhots of screens and composite them.

* **NativeScreenCopyHelper.cs** - similar to CsWin32CopyHelper, but using manually defined Win32 API calls to reduce dependency on CsWin32

I've timed each of these methods 100 times using a contrived screen layout which includes 4 virtual monitors managed by a tool called **usbmmidd_v2** downloadable from https://www.amyuni.com/forum/viewtopic.php?t=3030

![image](https://user-images.githubusercontent.com/1193763/222544262-ee1fe6cd-46e2-46b9-89d5-d7b7098040ad.png)

Average timings are as follows:

| Method | Average Time |
| -- | --: |
| DefaultScreenCopyHelper.cs | 1900ms |
| ScalingScreenHelper.cs | 3430ms |
| CsWin32JigsawCopyHelper.cs | 580ms |
| ParallelScreenCopyHelper.cs | 580ms |
| NativeScreenCopyHelper.cs | 630ms |

![image](https://user-images.githubusercontent.com/1193763/222551277-d3b04093-b508-4f5e-92c1-7624f03f32ed.png)

Based on the above, I'm going to cut over to the NativeScreenCopyHelper rather than ParallelScreenCopyHelper for now as the difference is negligible and NativeScreenCopyHelper is simpler.

**Comment by mikeclayton** [comment]
Switched to NativeScreenCopyHelper  in FancyMouse v0.0.10-preview - see https://github.com/mikeclayton/FancyMouse/releases/tag/v0.0.10-preview
