### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by oSumAtrIX** [mikeclayton/FancyMouse#6]
## Issue

After the shortcut is triggered, there is a noticeable delay until the window with all the screens opens (probably #4).

## Solutions

- https://github.com/mikeclayton/FancyMouse/issues/4#issuecomment-1451313731

## Motivation

The delay is so long, that it is faster to just move the mouse across screens, rendering the jump useless.

**Comment by mikeclayton** [comment]
I've got an update waiting that uses the Win32 API [StretchBlt](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-stretchblt) function which is a fair bit faster than the existing dotnet [CopyFromScreen](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.graphics.copyfromscreen?view=dotnet-plat-ext-7.0) method, but I've not had a chance to push / merge it yet.

I'll try to do that over the next couple of days, but here's a teaser of the increase for my deliberately awful test screen layout...

![image](https://user-images.githubusercontent.com/1193763/222409715-fb183276-accf-42f4-a9ad-488402b7e822.png)

Performance comparison across 100 iterations (time taken vs frequency):

![image](https://user-images.githubusercontent.com/1193763/222409845-27f299a2-a609-4060-a008-5984e310d9c0.png)

Horizontal axis is time taken - slower methods are further right, vertical axis is count of times per 50ms bucket.

Summary:

* ```CopyFromDesktop``` (yellow line) is slow (further right) and performance varies (shorter  / wider spread of results)
* ```StretchBlt``` (left-hand peaks) to scale natively and a "Jigsaw" method to snapshot each screen areas and composite them is faster (faster and tighter spread of results)

**Comment by mikeclayton** [comment]
@oSumAtrIX - I've changed the method used to generate the screenshot in v0.0.10-preview which is available to download from the Releases page now.

From my testing it's a fair bit snappier - I don't think it will ever be *instant* but the delay should be significantly less than it was, if you're able to test and confirm if it's improved for you?

I'll leave this issue open for a few days just in case there's still problems...

**Comment by mikeclayton** [comment]
Closing ticket...
